// ****************************************************************************
// This file is part of the Integrating Vision Toolkit (IVT).
//
// The IVT is maintained by the Karlsruhe Institute of Technology (KIT)
// (www.kit.edu) in cooperation with the company Keyetech (www.keyetech.de).
//
// Copyright (C) 2012 Karlsruhe Institute of Technology (KIT).
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the KIT nor the names of its contributors may be
//    used to endorse or promote products derived from this software
//    without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE KIT AND CONTRIBUTORS “AS IS” AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE KIT OR CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// ****************************************************************************
// ****************************************************************************
// Filename:  MainWindowEventInterface.h
// Author:    Florian Hecht
// Date:      2008
// ****************************************************************************


#ifndef _MAIN_WINDOW_EVENT_INTERFACE_H_
#define _MAIN_WINDOW_EVENT_INTERFACE_H_


// ****************************************************************************
// Necessary includes
// ****************************************************************************

#include "MainWindowInterface.h"


// ****************************************************************************
// Defines
// ****************************************************************************

#define IVT_LEFT_BUTTON		0
#define IVT_RIGHT_BUTTON	1
#define IVT_MIDDLE_BUTTON	2



// ****************************************************************************
// CMainWindowEventInterface
// ****************************************************************************

/*!
	\ingroup GUI
	\brief Interface for the event mechanism of GUIs using the GUI toolkit of the IVT.
*/
class CMainWindowEventInterface
{
public:
	// destructor
	virtual ~CMainWindowEventInterface() { }


	// public methods

	// this two events are specific for the image widget
	virtual void RectSelected(WIDGET_HANDLE widget, int x0, int y0, int x1, int y1) { }
	virtual void PointClicked(WIDGET_HANDLE widget, int x, int y) { }
	
	// the following events are only generated for image and GL widgets
	virtual void MouseDown(WIDGET_HANDLE widget, int button, int x, int y) { }
	virtual void MouseUp(WIDGET_HANDLE widget, int button, int x, int y) { }
	virtual void MouseMove(WIDGET_HANDLE widget, int x, int y) { }
	virtual void KeyDown(WIDGET_HANDLE widget, int key) { }
	virtual void KeyUp(WIDGET_HANDLE widget, int key) { }

	// this event is only emitted for buttons
	virtual void ButtonPushed(WIDGET_HANDLE widget) { }

	// this event is generated by check boxes, sliders, text edits (value = -1)
	// and combo boxes
	virtual void ValueChanged(WIDGET_HANDLE widget, int value) { }
};



#endif /* _MAIN_WINDOW_EVENT_INTERFACE_H_ */
